# Generated by Django 4.2.4 on 2023-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('idchat', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=250)),
                ('recipient', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('date_sent', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
