# Generated by Django 4.2.4 on 2023-08-15 00:29
from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),

    ]

    operations = [
        migrations.AddField(
            model_name="chats",
            name="author",

        field=models.CharField(max_length=255,
    default= "valor_temporario"),
        )

    ]
