# Generated by Django 4.2.4 on 2023-08-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20230815_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
